### PR TITLE
Update docs links in README.md

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR updates links to docs and replaces mention of `Control Plane` with `management cluster`.

### CODE REVIEW

**Review by cokiengchiara — APPROVED** [review]
LGTM, thank you for taking care!

**Comment by ubergesundheit** [comment]
@cokiengchiara I also added a pull request template towards giantswarm/giantswarm#15148 Please re-review

**Comment by cokiengchiara** [comment]
> @cokiengchiara I also added a pull request template towards [giantswarm/giantswarm#15148](https://github.com/giantswarm/giantswarm/issues/15148) Please re-review

sure. LGTM. But based on previous experience, the problem with this is not that we don't have docs but because team found it too much of a hassle to actually use... so I think @webwurst and @ced0ps 's review would be more useful here.

**Comment by ubergesundheit** [comment]
this pr is mainly for housekeeping, just added some stuff I found useful :)

**Comment by ubergesundheit** [comment]
@webwurst @ced0ps merging with a ping

**Pull request merged**
